# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7ef2ccecb48055f16ed107e947af0b4e54eb2d97a9d6b0dad442b30936f013502174b697287a39214ac29b82c970c46a256416f0ffaa6183e881b61e2ee66415

test:
  secret_key_base: a2b1a79abfcf7564b5a3f7ccf69068321838a50654f7860afe12ad78e4659d3435377eea8e4278b411fe57d09c8d323a942e483c5dee677544043f88ed540402

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
